#!/bin/bash
# Record contents of /etc/passwd and group in checked-in, backed-up files
set -e
cd /var/lib/server-state/
for file in passwd group ; do
    cat /etc/$file > ./$file.new
    if [ -e $file ] ; then
        if ! diff $file $file.new > /dev/null ; then
            mv $file.new $file
            git add $file
            git commit --quiet -m "save-passwd-group: /etc/${file} on $(hostname) has changed"
        else
            rm -f $file.new
        fi
    else
        mv $file.new $file
        git add $file
        git commit --quiet -m "save-passwd-group: initial commit of /etc/${file} on $(hostname)"
    fi
done
