#!/bin/bash
# Record list of packages in checked in, backed up file
set -e
msg="save-package-list: packages installed on $(hostname) changed"
cd /var/lib/server-state/
COLUMNS=1000 /usr/bin/dpkg -l | tail -n +6 | egrep "^ii " | awk '{print $1" "$2" "$3}' > ./packages.new
if [ -e packages ] ; then
    if ! diff packages packages.new > /dev/null ; then
        mv packages.new packages
        git add packages
        git commit --quiet -m "$msg"
    else
        rm packages.new
    fi
else
    mv packages.new packages
    git add packages
    git commit --quiet -m "$msg"
fi
