#!/bin/bash
#
# git-shared-fixperms - call this via `sudo` from a relevant git hook.
#

# There might be files owned by other users, so exit unless root
# as otherwise the chmod calls might fail.
[ "$UID" -ne "0"  ] && exit 1

# Let's not do anything unless we're in a git repository.
ROOT=$(git rev-parse --show-cdup 2>/dev/null) || exit 2

# Assuming we're root and working in a git repo, fix those perms.
find $ROOT -type d -exec chmod g+ws {} \;
find $ROOT -type f -exec chmod g+w {} \;

